#!/bin/bash
javaVersion=$1

if [ -z "$javaVersion" ];then
  javaVersion="21"
  echo "No javaVersion provided, use default jdk$javaVersion"
fi

if [[ "$javaVersion" == "17" ]];then
  export JAVA_HOME=$JAVA17_HOME
elif [[ "$javaVersion" == "8" ]];then
  export JAVA_HOME=$JAVA8_HOME
elif [[ "$javaVersion" == "11" ]];then
  export JAVA_HOME=$JAVA11_HOME
elif [[ "$javaVersion" == "21" ]];then
  export JAVA_HOME=$JAVA21_HOME
else
  echo "Unsupported javaVersion $javaVersion"
  return
fi

export MAVEN_OPTS="-Xmx512m -Xms128m"
export PATH=$JAVA_HOME/bin:$MVND_HOME/bin:$PATH

if [ -z "$MVND_HOME" ];then
    echo "MVND_HOME is not set, mvnd can speed up local build, see https://github.com/apache/maven-mvnd. (mvnd currently does not update plugins on each run, when developing maven plugin, use mvnw)"
    java -javaVersion
else
    mvnd -javaVersion
fi
