// Code generated by https://github.com/SharedType/sharedtype

// test code snippet
export interface CustomCode {
}


export interface MyClass {
    readonly value: number;
}

export interface MyClass2<T> {
    readonly value: T;
}

