name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  style_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: style_check_maven
      - name: Check Format
        run: ./mvnw editorconfig:check

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: build_and_test_maven
      - name: Build
        run: ./mvnw compile -e
      - name: Test
        run: ./mvnw test -e
      - uses: actions/upload-artifact@v4
        with:
          name: generated-sources
          path: |
            it/target/generated-sources/*
          if-no-files-found: error

  client_test:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/download-artifact@v4
        with:
          name: generated-sources
          path: it/target/generated-sources/
      - name: Display downloaded artifact
        run: ls -lhR it/target/generated-sources
      - name: Test Typescript
        working-directory: client-test/typescript
        run: |
          npm i
          npm run test

  clean-artifact:
    needs: [ client_test ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: dist
