name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: manual-maven
          restore-keys: |
            manual-maven
      - name: Build
        run: ./mvnw compile -e
      - name: Test
        run: ./mvnw test -e

  clean-artifact:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: dist
